###
POST http://localhost:8080/project/members
Content-Type: application/json

{
  "accountId": 7,
  "projectId": 3,
  "roleId": 1
}

###
GET http://localhost:8080/project/members/7

###
DELETE http://localhost:8080/project/members/7/3