###
POST http://localhost:9090/milestones
Content-Type: application/json

{
  "projectId": 1,
  "mileStoneName": "task API 구현",
  "mileStoneStartDate": "2023-06-20",
  "mileStoneEndDate": "2023-06-30"
}
###

GET http://localhost:9090/milestones/1

###
