###
POST http://localhost:9090/projects
Content-Type: application/json

{
  "projectName": "게시판 만들기",
  "accountId": 1,
  "projectStatusId": 1
}

###
PUT http://localhost:9090/projects/4/name
Content-Type: application/json

{
  "projectName": "게시판 5조"
}

###
PUT http://localhost:9090/projects/4/status
Content-Type: application/json

{
  "projectStatusId": 2
}

###
GET http://localhost:9090/projects/1/members