POST http://localhost:9090/projects
Content-Type: application/json

{
  "projectName": "게시판 만들기",
  "accountId": 1,
  "projectStatusId": 1
}

###

POST http://localhost:9090/project/members
Content-Type: application/json

{
  "accountId": 7,
  "projectId": 3,
  "roleId": 1
}

###

GET http://localhost:9090/project/members/7

###

